---
title: "Leadership"
output: html_document
---

HerbVar was founded by the [Wetzel Lab at Michigan State University](https://WetzelLab.com) and is led by a Steering Group and multiple Subgroups that focus on specific topics.

## HerbVar Steering Group

**Dr. Will Wetzel**  
Department of Entomology  
Ecology, Evolutionary Biology, & Behavior Program  
Michigan State University  
wcwetzel (a) msu.edu • [website](https://WetzelLab.com)  
  

**Dr. Moria Robinson**  
Department of Entomology  
Ecology, Evolutionary Biology, & Behavior Program  
Michigan State University  
robi1169 (a) msu.edu • [website](https://www.moriarobinson.com/)  
  

**Dr. Lee Dyer**  
Department of Biology  
Ecology, Evolution and Conservation Program  
Univesity of Nevada, Reno  
ldyer (a) unr.edu • [website](https://www.unr.edu/biology/people/lee-dyer)  
  

**Dr. Phil Hahn**  
Department of Entomology & Nematology
University of Florida  
phil.hahn (a) mso.umt.edu • [website](https://plant-herbivore-interactions.net/)

**Dr. Brian Inouye**  
Florida State University  


**Dr. Nora Underwood**  
Florida State University  


**Dr. Susan Whitehead**  
Virginia Tech  

